name: MX-CustomGUI
version: '1.0-SNAPSHOT'
main: org.skyzzin.MxCustomGui
api-version: '1.21'
authors: [ Skyzzin ]
description: Plugin De Interface Grafica
website: https://github.com/skyzzin

commands:

  cgui:
    usage: /cgui chest
    description: Criar Interface Customizada

  opengui:
    usage: /opengui <NameCustomGUI>
    description: Abrir Interface Customizada

  lgui:
    usage: /lgui
    description: Listar todas as GUIs criadas

  dgui:
    usage: /dgui
    description: Deletar Gui Criada